media:
  # where PagesCMS will drop uploads
  - name: rank-utah
    label: rank-utah media
    input:  sites/rank-utah/assets/media
    # how they’ll be referenced in your site
    output: /media

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: tags, label: Tags, type: string } 
      - { name: body,  label: Body, type: rich-text, required: true}

components: {}
