media:
  - name: rank-utah
    label: rank-utah media
    input: sites/rank-utah/assets/media
    output: /media

components:
  titleField:
    label: Title
    type: string
    required: true
    description: >
      Include your city or a nearby landmark in your title to drive more local traffic

  tagsField:
    label: Tags
    type: select
    options:
      multiple: true
      creatable: true
      placeholder: "Add tags…"
      max: 5
    description: >
      Use as few tags as necessary (lowercase, singular, hyphens for multi-word)
      to help visitors find related content and keep your site organized.

  bodyField:
    label: Body
    type: rich-text
    required: true
    description: >
      Use the `/` command to insert images, embeds, and headings.  
      After adding an image, click it and add a brief alt-text
      (e.g. “People watching fireworks in Salt Lake City”) to improve
      accessibility & discoverability.  
      Structure with H2–H3 headings (your Title is already H1).

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"

    view:
      fields: [ title, date, is_published, tags ]
      sort: [ date ]
      default:
        sort: date
        order: desc

    fields:
      - name: title
        component: titleField

      - name: is_published
        label: Status
        type: select
        required: true
        options:
          values:
            - Draft
            - Published
          default: Draft
        description: >
          Select “Published” when your post is ready, then click “Save” to publish.

      - name: tags
        component: tagsField
        options:
          fetch:
            url: https://spotlight.rankutah.com/tags/tags.json
            method: GET
            results: ""

      - name: body
        component: bodyField

      - name: date
        label: Date
        type: date
        required: false
        default: "{{ now }}"
        description: >
          Auto-populated to today’s date. Change only if you need to backdate a post.
