media:
  - name: rank-utah
    label: rank-utah media
    input: sites/rank-utah/assets/media
    output: /media

components:
  titleField:
    label: Title
    type: string
    required: true
    description: |
      Include your city or a nearby landmark in your title to drive more local traffic

  dateField:
    label: Date
    type: date
    required: true
    description: |
      Pick today’s date, or change it if you need to backdate your post.

  statusField:
    label: Status
    type: select
    required: true
    default: Draft
    options:
      values:
        - Draft
        - Published
    description: |
      Leave as “Draft” (default) to keep the post unpublished.
      Select “Published” to make it live, then click Save.

  tagsField:
    label: Tags
    type: select
    options:
      multiple: true
      creatable: true
      placeholder: "Add tags…"
    description: |
      Use as few tags as necessary (lowercase, singular, hyphens for multi-word)
      to help visitors find related content and keep your site organized.

  bodyField:
    label: Body
    type: rich-text
    required: true
    description: |
      Use the `/` command to insert images and headings.
      Highlight text to format or add links.
      After adding an image, click the image, click ALT, and enter a brief
      description of the image (e.g. “People watching fireworks in Salt Lake City”)
      to improve search traffic.
      Organize your content under subheadings for clear structure.

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"

    view:
      fields: [ date, is_published, title, tags ]
      sort:   [ date ]
      default:
        sort:  date
        order: desc

    fields:
      - name: title
        component: titleField

      - name: date
        component: dateField

      - name: is_published
        component: statusField

      - name: tags
        component: tagsField
        options:
          fetch:
            url: https://spotlight.rankutah.com/tags/tags.json
            method: GET
            results: ""

      - name: body
        component: bodyField
