media:
  # where PagesCMS will drop uploads
  - name: rank-utah
    label: rank-utah media
    input:  sites/rank-utah/assets/media
    # how they’ll be referenced in your site
    output: /media

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"
    fields:
      - name: title 
        label: Title 
        type: string 
        description: "Include your city or a nearby landmark in your title to drive more local traffic"
        required: true
      - name: tags 
        label: Tags
        type: select 
        options: 
          multiple: true
          creatable: true
          placeholder: "Create or select..."
        description: "Use as few tags as necessary (no more than five). Keep each tag lowercase and singular, and use hyphens for multi-word tags"
      - name: body  
        label: Body
        type: rich-text 
        required: true

components: {}
