media:
  # where PagesCMS will drop uploads
  - name: rank-utah
    label: rank-utah posts
    input:  sites/rank-utah/assets/media
    # how they’ll be referenced in your site
    output: /media

content:
  - name: rank-utah
    label: rank-utah media
    type: collection
    path: rank-utah/content/spotlights
    # new files: 2025-06-10-my-title.md
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - { name: title, label: Title,        type: string,    required: true }
      - { name: date,  label: Date,         type: date,      required: true }
      - { name: draft, label: Draft status, type: boolean }
      - { name: image, label: Header image, type: file }
      - { name: body,  label: Body,         type: rich-text }

components: {}
