media:
  - name: rank-utah
    label: rank-utah media
    input: sites/rank-utah/assets/media
    output: /media

components:
  titleField:
    label: Title
    type: string
    required: true
    description: >
      Include your city or a nearby landmark in your title to drive more local traffic

  tagsField:
    label: Tags
    type: select
    options:
      multiple: true
      creatable: true
      placeholder: "Add tags…"
      max: 5
      fetch:
        url: https://spotlight.rankutah.com/tags/tags.json
        method: GET
        results: ""     # root array of objects
    description: >
      Use as few tags as necessary (lowercase, singular, hyphens for multi-word)
      to help visitors find related content and keep your site organized.

  bodyField:
    label: Body
    type: rich-text
    required: true
    description: >
      Use the `/` command to insert images, embeds, and headings.  
      After adding an image, click it and add a brief alt-text
      (e.g. “People watching fireworks in Salt Lake City”) to improve
      accessibility & discoverability.  
      Structure with H2–H3 headings (your Title is already H1).

content:
  - name: rank-utah
    label: rank-utah posts
    type: collection
    path: sites/rank-utah/content/spotlights
    filename: "{primary}.md"

    # ───── CMS LIST VIEW CONFIG ─────
    view:
      fields: [ title, date, tags ]        # only show Title & Date columns
      sort: [ date ]                 # allow sorting by date
      default:
        sort: date                   # default sort column
        order: desc                  # newest first

    fields:
      - name: title
        component: titleField

      - name: date
        label: Date
        type: date
        required: false
        default: "{{ now }}"         # auto-filled with today’s date
        description: >
          Auto-populated to the publish date.  
          Change only if you need to backdate or schedule a future post.

      - name: tags
        component: tagsField

      - name: body
        component: bodyField
