baseURL       = "https://blog.rankutah.com/"
languageCode  = "en-us"
title         = "Spotlight Utah"
theme         = "PaperMod"

# Tell Hugo to produce a JSON index for search
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  accentColor     = "#f3844b"
  showReadingTime = true
  enableSearch    = true

[taxonomies]
  tag = "tags"

[menu]

  [[menu.main]]
    name       = "Home"
    url        = "/"
    weight     = 1
  
  [[menu.main]]
    name       = "About"
    url        = "/about/"
    weight     = 2

#  [[menu.main]]
#    name       = "Posts"
#    url        = "/posts/"
#    weight     = 2

#  [[menu.main]]
#    name       = "Tags"
#    url        = "/tags/"
#    weight     = 3

#  [[menu.main]]
#    name       = "Archives"
#    url        = "/archives/"
#    weight     = 4

  [[menu.main]]
    name       = "Search"
    url        = "/search/"
    weight     = 3
