# ─────────────────────────────────────────────────────────────────────────────
baseURL       = "https://spotlight.rankutah.com/"
languageCode  = "en-us"
title         = "Spotlight Utah"
themesDir     = "../themes"
theme = [ "shared-blog", "PaperMod" ]

# ─────────────────────────────────────────────────────────────────────────────

pruneTaxonomies = true

# Tell Hugo to produce a JSON index for search
[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  googleAnalyticsID = "G-LGYK5V1CTV"
  accentColor     = "#f3844b"
  showReadingTime = true
  enableSearch    = true
  clientName = "Rank Utah"
  clientURL = "https://rankutah.com"
  mainSections = ["spotlights"]

[permalinks]
  spotlights = "/:slug/"

[taxonomies]
  tag = "tags"

[menu]

  [[menu.main]]
    name       = "Spotlights"
    url        = "/"
    weight     = 1

  # [[menu.main]]
  #   name       = "Posts"
  #   url        = "/highlights/"
  #   weight     = 2

  [[menu.main]]
    name       = "Tags"
    url        = "/tags/"
    weight     = 2

  [[menu.main]]
    name       = "About"
    url        = "/about/"
    weight     = 3

  # [[menu.main]]
  #   name       = "Archives"
  #   url        = "/archives/"
  #   weight     = 4

  [[menu.main]]
    name       = "Search"
    url        = "/search/"
    weight     = 5
