backend:
  name: git-gateway
  branch: main

collections:
  - name: "spotlights"
    label: "Spotlights"
    folder: "content/spotlights"
    create: true
    slug: "{{slug}}/index"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Tags (optional)"
        name: "tags"
        widget: "list"
        required: false
        default: []
