backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "spotlights"
    label: "Spotlights"
    folder: "content"
    create: true
    slug: "{{slug}}.md"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Tags (optional)"
        name: "tags"
        widget: "list"
        required: false
        default: []
      - label: "Body"
        name: "body"
        widget: "markdown"
