backend:
  name: github
  repo: your-github-username/your-repo
  branch: main
  site_domain: spotlightblog.netlify.app


media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "spotlights"
    label: "Spotlights"
    folder: "content/spotlights"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }

