backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "spotlights"
    label: "Spotlights"
    folder: "content/spotlights"
    create: true
    slug: "{{slug}}/index"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body",  name: "body",  widget: "markdown" }
      - label: "Tags"
        name: "tags"
        widget: "tags"
        required: false
