backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "spotlights"
    label: "Spotlights"
    folder: "content/spotlights"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title (Please add city or landmark for local SEO)", name: "title", widget: "string" }
      - label: "Tags (Add comma with no space for additional tags)"
        name: "tags"
        widget: "list"
        required: false
        default: []
      - label: "Body"
        name: "body"
        widget: "markdown"
